spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    url: userdetails.cebdnrrkrbxu.ap-northeast-1.rds.amazonaws.com
    password: rootroot
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
server:
  port: '8082'

