
spring:
  datasource:
<<<<<<< HEAD:MicroServices/UserDetails/src/main/resources/application.yml
    driver-class-name: com.mysql.jdbc.Driver
=======
    
>>>>>>> main:MicroServices/userslist/src/main/resources/application.yml
    username: admin
    url: jdbc:mysql://database-2.cebdnrrkrbxu.ap-northeast-1.rds.amazonaws.com:3306/users
    password: rootroot
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8082'

