
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    url: jdbc:mysql://database-2.cebdnrrkrbxu.ap-northeast-1.rds.amazonaws.com:3306/users
    password: rootroot
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: 8082

